# Generated by Django 6.0.1 on 2026-01-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtracker',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='applicationtracker',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationtracker',
            unique_together={('student', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('student', 'job')},
        ),
    ]
