# Generated by Django 6.0.1 on 2026-02-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.skill'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('part_time', 'Part-time'), ('graduate', 'Graduate'), ('full_time', 'Full-time')], default='graduate', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
