"""
Static list of course/degree names for sign-up and profile.
Can be replaced later with an API (e.g. HESA/UCAS) or DB table.
"""

COURSES = [
    # Tech & computing
    "Computer Science",
    "Information Technology",
    "Software Engineering",
    "Data Science",
    "Cybersecurity",
    "Business Information Systems",
    "Artificial Intelligence",
    "Computer Games Development",
    "Web Development",
    "Digital Media Technology",
    # Engineering
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aeronautical Engineering",
    "Biomedical Engineering",
    "Electronic Engineering",
    "Environmental Engineering",
    "Industrial Engineering",
    # Business & management
    "Business Management",
    "Business Studies",
    "Accounting",
    "Accounting and Finance",
    "Economics",
    "Finance",
    "Marketing",
    "Human Resource Management",
    "International Business",
    "Management",
    # Arts & humanities
    "English Literature",
    "History",
    "Philosophy",
    "Politics",
    "Sociology",
    "Psychology",
    "Geography",
    "Law",
    "Criminology",
    "Media and Communications",
    "Journalism",
    "Creative Writing",
    "Art and Design",
    "Music",
    "Drama",
    "Film Studies",
    # Sciences
    "Biology",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Biochemistry",
    "Biomedical Science",
    "Environmental Science",
    "Natural Sciences",
    "Sports Science",
    "Nursing",
    "Medicine",
    "Pharmacy",
    "Veterinary Science",
    # Education & social
    "Education",
    "Primary Education",
    "Secondary Education",
    "Social Work",
    "Early Childhood Studies",
    # Other
    "Architecture",
    "Construction Management",
    "Hospitality Management",
    "Tourism Management",
    "Sports Management",
    "Other",
]
