"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY / ENV
# ============================================================

# IMPORTANT: set SECRET_KEY in Render Environment
SECRET_KEY = config("SECRET_KEY", default="django-insecure-dev-only")

# IMPORTANT: set DEBUG=False in Render Environment
DEBUG = config("DEBUG", default=True, cast=bool)

# IMPORTANT: set ALLOWED_HOSTS in Render Environment
# Example value:
# studentjobrecommender.onrender.com,.onrender.com,localhost,127.0.0.1
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="studentjobrecommender.onrender.com,.onrender.com,localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
)

# Safety net: never allow empty ALLOWED_HOSTS in production by mistake
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = [
        "studentjobrecommender.onrender.com",
        ".onrender.com",
        "localhost",
        "127.0.0.1",
    ]


# ============================================================
# APPLICATION DEFINITION
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",

    # Local apps
    "users.apps.UsersConfig",
    "jobs",
    "recommendations",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ============================================================
# CORS / CSRF (IMPORTANT FOR REACT FRONTEND)
# ============================================================

# Recommended: allow only your frontend domains
# Set on Render:
# CORS_ALLOWED_ORIGINS=https://your-frontend.vercel.app,http://localhost:5173
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173",
    cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
)

# If you ever need cookies across domains, enable these:
# CORS_ALLOW_CREDENTIALS = True

# Trusted origins for CSRF (mainly needed if you use Session auth/admin/cookies)
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://studentjobrecommender.onrender.com,http://localhost:5173",
    cast=lambda v: [s.strip() for s in v.split(",") if s.strip()],
)

# ============================================================
# AUTH / REST FRAMEWORK
# ============================================================

AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
