"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config
import dj_database_url  # Make sure to install this: pip install dj-database-url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# DEBUG: Print that settings are loading (visible in Render logs)
print(f"=== Loading Django settings from: {__file__} ===", file=sys.stderr)
print(f"BASE_DIR: {BASE_DIR}", file=sys.stderr)
print(f"Current working directory: {os.getcwd()}", file=sys.stderr)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)0jj4t6jft(hsgx6d($9j*$)#1-6$p&+8suibs44&dw&x2wkjs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# DYNAMIC ALLOWED_HOSTS CONFIGURATION
# This ensures Render.com hosts are always allowed
ALLOWED_HOSTS = []

# Always add local development hosts
ALLOWED_HOSTS.extend([
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
])

# Add Render.com specific hosts
RENDER_HOSTS = [
    'studentjobrecommender.onrender.com',
    '.onrender.com',  # This allows all subdomains on render.com
    '*.onrender.com',  # Alternative wildcard syntax
]

# Get the specific Render hostname from environment if available
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    print(f"Found RENDER_EXTERNAL_HOSTNAME: {render_external_hostname}", file=sys.stderr)
    RENDER_HOSTS.append(render_external_hostname)
    # Also add with wildcard for subdomains
    if render_external_hostname.startswith('.'):
        RENDER_HOSTS.append(render_external_hostname)
    else:
        RENDER_HOSTS.append(f'.{render_external_hostname}')

# Get the Render service name if available
render_service_name = os.environ.get('RENDER_SERVICE_NAME')
if render_service_name:
    print(f"Found RENDER_SERVICE_NAME: {render_service_name}", file=sys.stderr)
    render_url = f"{render_service_name}.onrender.com"
    RENDER_HOSTS.append(render_url)
    RENDER_HOSTS.append(f'.{render_url}')

# Add any hosts from environment variable (comma-separated list)
extra_hosts = os.environ.get('ADDITIONAL_ALLOWED_HOSTS', '')
if extra_hosts:
    for host in extra_hosts.split(','):
        host = host.strip()
        if host:
            RENDER_HOSTS.append(host)

# Remove duplicates while preserving order
ALLOWED_HOSTS.extend(list(dict.fromkeys(RENDER_HOSTS)))

print(f"Final ALLOWED_HOSTS: {ALLOWED_HOSTS}", file=sys.stderr)
print("="*50, file=sys.stderr)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    
    'users.apps.UsersConfig',
    'jobs',
    'recommendations',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database Configuration
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Check if we're running on Render
if 'RENDER' in os.environ:
    # On Render, use the DATABASE_URL environment variable
    print("🚀 Running on Render - using DATABASE_URL", file=sys.stderr)
    print(f"📊 DATABASE_URL: {os.environ.get('DATABASE_URL', 'Not set')}", file=sys.stderr)
    
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,  # Render requires SSL
        )
    }
else:
    # Local development - use .env file with python-decouple
    print("💻 Running locally - using .env file", file=sys.stderr)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

print(f"✅ Database configured. Host: {DATABASES['default'].get('HOST', 'Not set')}", file=sys.stderr)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Enable WhiteNoise compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    )
}